### ISSUE TITLE
Faster file transfer?

### ISSUE THREAD

**Issue by inful** [marithetland/susCovONT#6]
This might be worth a try: https://arjon.es/2017/which-is-the-best-tool-for-copying-a-large-directory-tree-locally/

Going the rsync route should also remove the need for doing md5sum checks.

**Comment by marithetland** [comment]
We did use rsync initially but it took much longer than just the simple cp + check md5sums afterwards. Will look at rsync + parallel though to see if that speeds up the process, thanks for the suggestion @inful.
